export enum MedicalSpecialty {
  ALERGIA_E_IMUNOLOGIA = 'Alergia e Imunologia',
  ANESTESIOLOGIA = 'Anestesiologia',
  ANGIOLOGIA = 'Angiologia',
  CANCEROLOGIA_CLINICA = 'Cancerologia Clínica',
  CANCEROLOGIA_CIRURGICA = 'Cancerologia Cirúrgica',
  CANCEROLOGIA_PEDIATRICA = 'Cancerologia Pediátrica',
  CARDIOLOGIA = 'Cardiologia',
  CIRURGIA_CARDIOVASCULAR = 'Cirurgia Cardiovascular',
  CIRURGIA_DA_MAO = 'Cirurgia da Mão',
  CIRURGIA_DE_CABECA_E_PESCOCO = 'Cirurgia de Cabeça e Pescoço',
  CIRURGIA_DO_APARELHO_DIGESTIVO = 'Cirurgia do Aparelho Digestivo',
  CIRURGIA_GERAL = 'Cirurgia Geral',
  CIRURGIA_ONCOLOGICA = 'Cirurgia Oncológica',
  CIRURGIA_PEDIATRICA = 'Cirurgia Pediátrica',
  CIRURGIA_PLASTICA = 'Cirurgia Plástica',
  CIRURGIA_TORACICA = 'Cirurgia Torácica',
  CIRURGIA_VASCULAR = 'Cirurgia Vascular',
  CLINICA_MEDICA = 'Clínica Médica',
  DERMATOLOGIA = 'Dermatologia',
  ENDOCRINOLOGIA_E_METABOLOGIA = 'Endocrinologia e Metabologia',
  ENDOSCOPIA = 'Endoscopia',
  GASTROENTEROLOGIA = 'Gastroenterologia',
  GERIATRIA = 'Geriatria',
  GINECOLOGIA_E_OBSTETRICIA = 'Ginecologia e Obstetrícia',
  HEMATOLOGIA_E_HEMOTERAPIA = 'Hematologia e Hemoterapia',
  HOMEOPATIA = 'Homeopatia',
  INFECTOLOGIA = 'Infectologia',
  MASTOLOGIA = 'Mastologia',
  MEDICINA_DE_EMERGENCIA = 'Medicina de Emergência',
  MEDICINA_DE_FAMILIA_E_COMUNIDADE = 'Medicina de Família e Comunidade',
  MEDICINA_DO_TRABALHO = 'Medicina do Trabalho',
  MEDICINA_ESPORTIVA = 'Medicina Esportiva',
  MEDICINA_FISICA_E_REABILITACAO = 'Medicina Física e Reabilitação',
  MEDICINA_INTENSIVA = 'Medicina Intensiva',
  MEDICINA_LEGAL = 'Medicina Legal',
  MEDICINA_NUCLEAR = 'Medicina Nuclear',
  MEDICINA_PREVENTIVA_E_SOCIAL = 'Medicina Preventiva e Social',
  NEFROLOGIA = 'Nefrologia',
  NEUROCIRURGIA = 'Neurocirurgia',
  NEUROLOGIA = 'Neurologia',
  NUTROLOGIA = 'Nutrologia',
  OFTALMOLOGIA = 'Oftalmologia',
  ONCOLOGIA_CLINICA = 'Oncologia Clínica',
  ORTOPEDIA_E_TRAUMATOLOGIA = 'Ortopedia e Traumatologia',
  OTORRINOLARINGOLOGIA = 'Otorrinolaringologia',
  PATOLOGIA = 'Patologia',
  PATOLOGIA_CLINICA_E_MEDICINA_LABORATORIAL = 'Patologia Clínica e Medicina Laboratorial',
  PEDIATRIA = 'Pediatria',
  PNEUMOLOGIA = 'Pneumologia',
  PSIQUIATRIA = 'Psiquiatria',
  RADIOLOGIA_E_DIAGNOSTICO_POR_IMAGEM = 'Radiologia e Diagnóstico por Imagem',
  RADIOTERAPIA = 'Radioterapia',
  REUMATOLOGIA = 'Reumatologia',
  UROLOGIA = 'Urologia',
}

export const medicalEspecialties = Object.entries(MedicalSpecialty).map(
  ([key, value]) => ({
    value: MedicalSpecialty[key as keyof typeof MedicalSpecialty],
    label: value,
  })
)
